### ISSUE TITLE
Sleep: Invalid Time Interval in TransferCacheToSDCard

### ISSUE THREAD

**Issue by CyricPL** [silverthornne/steamdeckbash#2]
I'm pretty new to Linux, so very possibly user error here! When I attempt to run transferCacheToSDCard.sh, I get the below result after selecting 1 to proceed:

`=========================With all of that out of the way, do you wish to proceed?==========================

1) Yes
2) No
#? 1

Once more unto the breach, dear friends!

sleep: invalid time interval ‘’
Try 'sleep --help' for more information.
Timing out; couldn't find Steam games on your MicroSD card.
Yes, you may see a grep error if you repeat last command. It's not a serious issue.
Terminated
(143)(deck@steamdeck steamdeckbash)$ 
`
I was following your YouTube video, so I'm fairly confident I installed this to the correct directory, and I can 100% confirm there are a couple hundred gigs of games on my SD card. Any idea what is happening?

**Comment by silverthornne** [comment]
Sorry about that! I think I may have pushed some bad update while testing for the external storage issue as I also introduced the timeout to the transferCacheToSDCard script. I just updated it; please pull again. Just cd to the directory with the script and type git pull

If you get an error that you need to merge change that's probably because of chmod. If that happens to you, do git reset. Then do git pull. Sorry about the inconvenience!

**Comment by CyricPL** [comment]
Fixed! Thanks!

**Comment by silverthornne** [comment]
Fixed on f23d9f26
